# Generated by Django 5.2.6 on 2025-09-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="brand_primary",
            field=models.CharField(blank=True, default="#0d6efd", max_length=7),
        ),
        migrations.AddField(
            model_name="client",
            name="brand_secondary",
            field=models.CharField(blank=True, default="#6c757d", max_length=7),
        ),
        migrations.AddField(
            model_name="client",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="client",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
    ]
