# Generated by Django 5.2.6 on 2025-09-15 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_client_brand_primary_client_brand_secondary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="brand_primary",
        ),
        migrations.RemoveField(
            model_name="client",
            name="brand_secondary",
        ),
        migrations.RemoveField(
            model_name="client",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="client",
            name="on_trial",
        ),
        migrations.AddField(
            model_name="client",
            name="brand_color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="client",
            name="user_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("ADMIN", "Admin"), ("MEMBER", "Member")],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenancy.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "client")},
            },
        ),
    ]
