# Generated by Django 5.2.6 on 2025-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_remove_client_brand_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="on_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="paid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="plan",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("teams", "Teams"),
                    ("enterprise", "Enterprise"),
                ],
                default="standard",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
